/* Autogenerated with DRAKON Editor 1.14 */
#ifndef DRAGONSCHEME_H46292
#define DRAGONSCHEME_H46292

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>


typedef enum {FIXNUM} object_type;

typedef struct object {
    object_type type;
    union {
        struct {
            long value;
        } fixnum;
    } data;
} object;
object* alloc_object(
    void
);

void eat_whitespace(
    FILE *in
);

object* eval(
    object *exp
);

char is_delimiter(
    int c
);

char is_fixnum(
    object *obj
);

void main(
    void
);

object* make_fixnum(
    long value
);

int peek(
    FILE *in
);

object* read(
    FILE *in
);

void write(
    object* obj
);


#endif

