/* Autogenerated with DRAKON Editor 1.14 */
#include "dragonscheme.h"

object *the_empty_list;
object *false;
object *true;
object *symbol_table;
object *quote_symbol;
object *define_symbol;
object *set_symbol;
object *ok_symbol;
object *the_empty_environment;
object *the_global_environment;

object *cons(object *car, object *cdr);
object *car(object *pair);
object *cdr(object *pair);

object *read(FILE *in);
void write(object *obj);

#define BUFFER_MAX 1000
#define caar(obj)   car(car(obj))
#define cadr(obj)   car(cdr(obj))
#define cdar(obj)   cdr(car(obj))
#define cddr(obj)   cdr(cdr(obj))
#define caaar(obj)  car(car(car(obj)))
#define caadr(obj)  car(car(cdr(obj)))
#define cadar(obj)  car(cdr(car(obj)))
#define caddr(obj)  car(cdr(cdr(obj)))
#define cdaar(obj)  cdr(car(car(obj)))
#define cdadr(obj)  cdr(car(cdr(obj)))
#define cddar(obj)  cdr(cdr(car(obj)))
#define cdddr(obj)  cdr(cdr(cdr(obj)))
#define caaaar(obj) car(car(car(car(obj))))
#define caaadr(obj) car(car(car(cdr(obj))))
#define caadar(obj) car(car(cdr(car(obj))))
#define caaddr(obj) car(car(cdr(cdr(obj))))
#define cadaar(obj) car(cdr(car(car(obj))))
#define cadadr(obj) car(cdr(car(cdr(obj))))
#define caddar(obj) car(cdr(cdr(car(obj))))
#define cadddr(obj) car(cdr(cdr(cdr(obj))))
#define cdaaar(obj) cdr(car(car(car(obj))))
#define cdaadr(obj) cdr(car(car(cdr(obj))))
#define cdadar(obj) cdr(car(cdr(car(obj))))
#define cdaddr(obj) cdr(car(cdr(cdr(obj))))
#define cddaar(obj) cdr(cdr(car(car(obj))))
#define cddadr(obj) cdr(cdr(car(cdr(obj))))
#define cdddar(obj) cdr(cdr(cdr(car(obj))))
#define cddddr(obj) cdr(cdr(cdr(cdr(obj))))
void add_binding_to_frame(
    object* var,
    object* val,
    object* frame
) {
    // item 748
    set_car(frame, cons(var, car(frame)));
    set_cdr(frame, cons(val, cdr(frame)));
    return;
    
}

object* alloc_object(
    void
) {
    // item 187
    object *obj;
    /* item 188 */
    obj = malloc(sizeof(object));
    
    // item 189
    if (obj == NULL) {
        /* item 192 */
        fprintf(stderr, "out of memory\n");
        /* item 193 */
        exit(1);
        return;
    } else {
        /* item 194 */
        return obj;
    }
    
}

object* car(
    object* pair
) {
    // item 480
    return pair->data.pair.car;
    
}

object* cdr(
    object *pair
) {
    // item 492
    return pair->data.pair.cdr;
    
}

object* cons(
    object* car,
    object* cdr
) {
    // item 466
    object *obj;
    /* item 467 */
    obj = alloc_object();
    obj->type = PAIR;
    obj->data.pair.car = car;
    obj->data.pair.cdr = cdr;
    /* item 468 */
    return obj;
    
}

void define_variable(
    object *var,
    object *val,
    object *env
) {
    // item 801
    object *frame;
    object *vars;
    object *vals;
    /* item 802 */
    frame = first_frame(env);    
    vars = frame_variables(frame);
    vals = frame_values(frame);
    
    item_803 :
    if (!is_the_empty_list(vars)) {
    } else {
        /* item 812 */
        add_binding_to_frame(var, val, frame);
        return;
    }
    
    // item 806
    if (var == car(vars)) {
        /* item 809 */
        set_car(vals, val);
        return;
    } else {
    }
    
    // item 811
    vars = cdr(vars);
    vals = cdr(vals);
    goto item_803;
    
}

void eat_expected_string(
    FILE *in,
    char *str
) {
    // item 277
    int c;
    
    item_278 :
    if (*str == '\0') {
        return;
    } else {
        /* item 280 */
        c = getc(in);
    }
    
    // item 281
    if (c == *str) {
        /* item 286 */
        str++;
        goto item_278;
    } else {
        /* item 284 */
        fprintf(stderr, 
        "unexpected character '%c'\n", c);
        /* item 285 */
        exit(1);
        return;
    }
    
}

void eat_whitespace(
    FILE *in
) {
    // item 126
    int c;
    
    item_130 :
    c = getc(in);
    
    // item 127
    if (c == EOF) {
        goto item_145;
    } else {
    }
    
    // item 131
    if (isspace(c)) {
        goto item_130;
    } else {
    }
    
    // item 133
    if (c == ';') {
    } else {
        goto item_145;
    }
    
    item_138 :
    c = getc(in);
    
    // item 136
    if ((c == EOF) || ((c == '\n'))) {
    } else {
        goto item_138;
    }
    
    item_145 :
    ungetc(c, in);
    return;
    
}

object* enclosing_environment(
    object* env
) {
    // item 717
    return cdr(env);
    
}

object* eval(
    object *exp
) {
    // item 694
    if (is_self_evaluating(exp)) {
        /* item 697 */
        return exp;
        goto item_704;
    } else {
    }
    
    // item 698
    if (is_quoted(exp)) {
        /* item 701 */
        return text_of_quotation(exp);
    } else {
        /* item 702 */
        fprintf(stderr, 
        "cannot eval unknown expression type\n");
        /* item 703 */
        exit(1);
    }
    
    item_704 :
    fprintf(stderr, "eval illegal state\n");
    /* item 705 */
    exit(1);
    return;
    
}

object* extend_environment(
    object *vars,
    object *vals,
    object *base_env
) {
    // item 754
    return cons(make_frame(vars, vals), base_env);
    
}

object* first_frame(
    object* env
) {
    // item 724
    return car(env);
    
}

object* frame_values(
    object* frame
) {
    // item 742
    return cdr(frame);
    
}

object* frame_variables(
    object* frame
) {
    // item 736
    return car(frame);
    
}

void init(
    void
) {
    // item 218
    false = alloc_object();
    false->type = BOOLEAN;
    false->data.boolean.value = 0;
    /* item 219 */
    true = alloc_object();
    true->type = BOOLEAN;
    true->data.boolean.value = 1;
    /* item 459 */
    the_empty_list = alloc_object();
    the_empty_list->type = THE_EMPTY_LIST;
    /* item 626 */
    symbol_table = the_empty_list;
    quote_symbol = make_symbol("quote");
    define_symbol = make_symbol("define");
    set_symbol = make_symbol("set!");
    ok_symbol = make_symbol("ok");
    /* item 821 */
    the_empty_environment = the_empty_list;
    the_global_environment = setup_environment();
    return;
    
}

char is_boolean(
    object *obj
) {
    // item 200
    return obj->type == BOOLEAN;
    
}

char is_character(
    object *obj
) {
    // item 271
    return obj->type == CHARACTER;
    
}

char is_delimiter(
    int c
) {
    // item 167
    return isspace(c) || c == EOF ||
               c == '('   || c == ')' ||
               c == '"'   || c == ';';
    
}

char is_false(
    object *obj
) {
    // item 206
    return obj == false;
    
}

char is_fixnum(
    object *obj
) {
    // item 173
    return obj->type == FIXNUM;
    
}

char is_initial(
    int c
) {
    // item 633
    return isalpha(c) || c == '*' || c == '/' || c == '>' ||
                 c == '<' || c == '=' || c == '?' || c == '!';
    
}

char is_pair(
    object* obj
) {
    // item 474
    return obj->type == PAIR;
    
}

char is_quoted(
    object* expression
) {
    // item 687
    return is_tagged_list(expression, quote_symbol);
    
}

char is_self_evaluating(
    object* exp
) {
    // item 669
    return is_boolean(exp) ||
    is_fixnum(exp)    ||
    is_character(exp) ||
    is_string(exp);
    
}

char is_string(
    object *obj
) {
    // item 378
    return obj->type == STRING;
    
}

char is_symbol(
    object *obj
) {
    // item 625
    return obj->type == SYMBOL;
    
}

char is_tagged_list(
    object* expression,
    object* tag
) {
    // item 675
    object *the_car;
    
    // item 676
    if (is_pair(expression)) {
        /* item 679 */
        the_car = car(expression);
        /* item 680 */
        return is_symbol(the_car) 
        && (the_car == tag);
    } else {
    }
    
    // item 681
    return 0;
    
}

char is_the_empty_list(
    object *obj
) {
    // item 440
    return obj == the_empty_list;
    
}

char is_true(
    object *obj
) {
    // item 212
    return !is_false(obj);
    
}

object* lookup_variable_value(
    object* var,
    object* env
) {
    // item 760
    object *frame;
    object *vars;
    object *vals;
    
    item_761 :
    if (is_the_empty_list(env)) {
        /* item 774 */
        fprintf(stderr, "unbound variable\n");
        /* item 775 */
        exit(1);
        return;
    } else {
        /* item 763 */
        frame = first_frame(env);
        vars = frame_variables(frame);
        vals = frame_values(frame);
    }
    
    item_764 :
    if (is_the_empty_list(vars)) {
        /* item 772 */
        env = enclosing_environment(env);
        goto item_761;
    } else {
    }
    
    // item 766
    if (var == car(vars)) {
        /* item 769 */
        return car(vals);
    } else {
    }
    
    // item 770
    vars = cdr(vars);
    vals = cdr(vals);
    goto item_764;
    
}

void main(
    void
) {
    // item 15
    printf("Welcome to Bootstrap Scheme. " 
    "Use ctrl-c to exit.\n");
    /* item 252 */
    init();
    
    item_19 :
    printf("> ");
    /* item 18 */
    write(eval(read(stdin)));
    /* item 20 */
    printf("\n");
    
    // item 21
    if (1) {
        goto item_19;
    } else {
        return;
    }
    
}

object* make_character(
    char value
) {
    // item 263
    object *obj;
    /* item 264 */
    obj = alloc_object();
    obj->type = CHARACTER;
    obj->data.character.value = value;
    /* item 265 */
    return obj;
    
}

object* make_fixnum(
    long value
) {
    // item 179
    object *obj;
    /* item 180 */
    obj = alloc_object();
    obj->type = FIXNUM;
    obj->data.fixnum.value = value;
    /* item 181 */
    return obj;
    
}

object* make_frame(
    object* variables,
    object* values
) {
    // item 730
    return cons(variables, values);
    
}

object* make_string(
    char* value
) {
    // item 364
    object *obj;
    /* item 365 */
    obj = alloc_object();
    obj->type = STRING;
    obj->data.string.value = malloc(strlen(value) + 1);
    
    // item 366
    if (obj->data.string.value == NULL) {
        /* item 369 */
        fprintf(stderr, "out of memory\n");
        /* item 370 */
        exit(1);
    } else {
    }
    
    // item 371
    strcpy(obj->data.string.value, value);
    /* item 372 */
    return obj;
    
}

object* make_symbol(
    char* value
) {
    // item 601
    object *obj;
    object *element;
    
    element = symbol_table;
    
    item_602 :
    if (is_the_empty_list(element)) {
        /* item 612 */
        obj = alloc_object();
        obj->type = SYMBOL;
        obj->data.symbol.value = malloc(strlen(value) + 1);
    } else {
        goto item_604;
    }
    
    // item 613
    if (obj->data.symbol.value == NULL) {
        /* item 616 */
        fprintf(stderr, "out of memory\n");
        /* item 617 */
        exit(1);
    } else {
    }
    
    // item 618
    strcpy(obj->data.symbol.value, value);
    symbol_table = cons(obj, symbol_table);
    /* item 619 */
    return obj;
    
    item_604 :
    if (strcmp(car(element)->data.symbol.value, value) == 0) {
        /* item 605 */
        return car(element);
    } else {
    }
    
    // item 608
    element = cdr(element);
    goto item_602;
    
}

int peek(
    FILE *in
) {
    // item 158
    int c;
    /* item 159 */
    c = getc(in);
    /* item 160 */
    ungetc(c,in);
    /* item 161 */
    return c;
    
}

void peek_expected_delimiter(
    FILE *in
) {
    // item 296
    if (is_delimiter(peek(in))) {
        return;
    } else {
        /* item 299 */
        fprintf(stderr, "character not followed by delimiter\n");
        /* item 300 */
        exit(1);
        return;
    }
    
}

object* read(
    FILE *in
) {
    // item 78
    int c;
    short sign = 1;
    long num = 0;
    char buffer[BUFFER_MAX];
    int i;
    /* item 79 */
    eat_whitespace(in);
    /* item 80 */
    c = getc(in);
    
    // item 227
    if (c == '#') {
        /* item 230 */
        c = getc(in);
    } else {
        goto item_84;
    }
    
    // item 2310001
    if (c == 't') {
        /* item 238 */
        return true;
        goto item_91;
    } else {
    }
    
    // item 2310002
    if (c == 'f') {
        /* item 239 */
        return false;
        goto item_91;
    } else {
    }
    
    // item 2310003
    if (c == '\\') {
        /* item 342 */
        return read_character(in);
        goto item_91;
    } else {
        /* item 241 */
        fprintf(stderr, 
        "unknown boolean literal\n");
        goto item_91;
    }
    
    item_84 :
    if (isdigit(c)) {
        /* item 93 */
        ungetc(c, in);
        goto item_100;
    } else {
    }
    
    // item 87
    if ((c == '-' && (isdigit(peek(in))))) {
        /* item 92 */
        sign = -1;
    } else {
        goto item_641;
    }
    
    item_100 :
    if (isdigit(c = getc(in))) {
        /* item 101 */
        num = (num * 10) + (c - '0');
        goto item_100;
    } else {
        /* item 104 */
        num *= sign;
    }
    
    // item 105
    if (is_delimiter(c)) {
        /* item 108 */
        ungetc(c, in);
        /* item 109 */
        return make_fixnum(num);
        goto item_91;
    } else {
        /* item 111 */
        fprintf(stderr, 
        "number not followed by delimiter\n");
        goto item_91;
    }
    
    item_641 :
    if (is_initial(c) ||
    ((c == '+' || c == '-') &&
    is_delimiter(peek(in)))) {
        /* item 645 */
        i = 0;
    } else {
        goto item_379;
    }
    
    item_646 :
    if (is_initial(c) || isdigit(c) ||
    c == '+' || c == '-') {
    } else {
        goto item_657;
    }
    
    // item 648
    if (i < BUFFER_MAX - 1) {
        /* item 651 */
        buffer[i++] = c;
    } else {
        /* item 652 */
        fprintf(stderr, "symbol too long. "
        "Maximum length is %d\n", BUFFER_MAX);
        /* item 653 */
        exit(1);
    }
    
    // item 654
    c = getc(in);
    goto item_646;
    
    item_657 :
    if (is_delimiter(c)) {
        /* item 660 */
        buffer[i] = '\0';
        ungetc(c, in);
        return make_symbol(buffer);
        goto item_91;
    } else {
        /* item 661 */
        fprintf(stderr, 
        "symbol not followed by delimiter. "
        "Found '%c'\n", c);
        exit(1);
        goto item_91;
    }
    
    item_379 :
    if (c == '"') {
        /* item 382 */
        i = 0;
    } else {
        goto item_444;
    }
    
    item_385 :
    c = getc(in);
    
    // item 386
    if (c == '"') {
        /* item 408 */
        buffer[i] = '\0';
        return make_string(buffer);
        goto item_91;
    } else {
    }
    
    // item 387
    if (c == '\\') {
        /* item 389 */
        c = getc(in);
    } else {
        goto item_395;
    }
    
    // item 391
    if (c == 'n') {
        /* item 394 */
        c = '\n';
    } else {
    }
    
    item_395 :
    if (c == EOF) {
        /* item 396 */
        fprintf(stderr, 
        "non-terminated string literal\n");
        /* item 398 */
        exit(1);
    } else {
    }
    
    // item 401
    if (i < BUFFER_MAX - 1) {
        /* item 402 */
        buffer[i++] = c;
        goto item_385;
    } else {
        /* item 404 */
        fprintf(stderr, 
        "string too long. Maximum length is %d\n",
        BUFFER_MAX);
        /* item 405 */
        exit(1);
        goto item_385;
    }
    
    item_444 :
    if (c == '(') {
        /* item 578 */
        return read_pair(in);
    } else {
    }
    
    // item 706
    if (c == '\'') {
        /* item 709 */
        return cons(quote_symbol, 
        cons(read(in), the_empty_list));
    } else {
    }
    
    // item 710
    fprintf(stderr, "bad input. Unexpected '%c'\n", c);
    exit(1);
    
    item_91 :
    exit(1);
    return;
    
}

object* read_character(
    FILE *in
) {
    // item 306
    int c;
    /* item 307 */
    c = getc(in);
    
    // item 3080001
    if (c == EOF) {
        /* item 315 */
        fprintf(stderr, "incomplete character literal\n");
        /* item 330 */
        exit(1);
        goto item_329;
    } else {
    }
    
    // item 3080002
    if (c == 's') {
    } else {
        goto item_3080003;
    }
    
    // item 316
    if (peek(in) == 'p') {
        /* item 319 */
        eat_expected_string(in, "pace");
        /* item 320 */
        peek_expected_delimiter(in);
        /* item 321 */
        return make_character(' ');
        goto item_329;
    } else {
        goto item_329;
    }
    
    item_3080003 :
    if ((c == 'n') && (peek(in) == 'e')) {
        /* item 324 */
        eat_expected_string(in, "ewline");
        /* item 325 */
        peek_expected_delimiter(in);
        /* item 326 */
        return make_character('\n');
    } else {
    }
    
    item_329 :
    peek_expected_delimiter(in);
    /* item 328 */
    return make_character(c);
    
}

object* read_pair(
    FILE *in
) {
    // item 543
    int c;
    object *car_obj;
    object *cdr_obj;
    /* item 544 */
    eat_whitespace(in);
    c = getc(in);
    
    // item 545
    if (c == ')') {
        /* item 548 */
        return the_empty_list;
    } else {
        /* item 549 */
        ungetc(c, in);
        car_obj = read(in);
        eat_whitespace(in);
        c = getc(in);
    }
    
    // item 550
    if (c == '.') {
        /* item 552 */
        c = peek(in);
    } else {
        /* item 568 */
        ungetc(c, in);
        cdr_obj = read_pair(in);        
        return cons(car_obj, cdr_obj);
    }
    
    // item 553
    if (is_delimiter(c)) {
        /* item 557 */
        cdr_obj = read(in);
        eat_whitespace(in);
        c = getc(in);
    } else {
        /* item 555 */
        fprintf(stderr, 
        "dot not followed by delimiter\n");
        /* item 556 */
        exit(1);
        return;
    }
    
    // item 569
    if (c == ')') {
        /* item 575 */
        return cons(car_obj, cdr_obj);
    } else {
        /* item 572 */
        fprintf(stderr,
        "where was the trailing right paren?\n");
        /* item 573 */
        exit(1);
        return;
    }
    
}

void set_car(
    object* obj,
    object* value
) {
    // item 486
    obj->data.pair.car = value;
    return;
    
}

void set_cdr(
    object* obj,
    object* value
) {
    // item 498
    obj->data.pair.cdr = value;
    return;
    
}

void set_variable_value(
    object* var,
    object* val,
    object* env
) {
    // item 781
    object *frame;
    object *vars;
    object *vals;
    
    item_782 :
    if (is_the_empty_list(env)) {
        /* item 785 */
        fprintf(stderr, "unbound variable\n");
        exit(1);
        return;
    } else {
        /* item 784 */
        frame = first_frame(env);
        vars = frame_variables(frame);
        vals = frame_values(frame);
    }
    
    item_786 :
    if (is_the_empty_list(vars)) {
        /* item 794 */
        env = enclosing_environment(env);
        goto item_782;
    } else {
    }
    
    // item 788
    if (var == car(vars)) {
        /* item 791 */
        set_car(vals, val);
        return;
    } else {
    }
    
    // item 792
    vars = cdr(vars);
    vals = cdr(vals);
    goto item_786;
    
}

object* setup_environment(
    void
) {
    // item 818
    object *initial_env;
    /* item 819 */
    initial_env = extend_environment(
                    the_empty_list,
                    the_empty_list,
                    the_empty_environment);
    /* item 820 */
    return initial_env;
    
}

object* text_of_quotation(
    object* exp
) {
    // item 693
    return cadr(exp);
    
}

void write(
    object* obj
) {
    int _sw290000_ = 0;
    int _sw4190000_ = 0;
    // item 358
    char c;
    char *str;
    /* item 290000 */
    _sw290000_ = obj->type;
    
    // item 290001
    if (_sw290000_ == FIXNUM) {
        /* item 35 */
        printf("%ld", obj->data.fixnum.value);
        return;
    } else {
    }
    
    // item 290002
    if (_sw290000_ == BOOLEAN) {
        /* item 223 */
        printf("#%c", is_false(obj) ? 'f' : 't');
        return;
    } else {
    }
    
    // item 290003
    if (_sw290000_ == CHARACTER) {
        /* item 347 */
        c = obj->data.character.value;
    } else {
        goto item_290004;
    }
    
    // item 3480001
    if (c == '\n') {
        /* item 355 */
        printf("newline");
        return;
    } else {
    }
    
    // item 3480002
    if (c == ' ') {
        /* item 356 */
        printf("space");
        return;
    } else {
        /* item 357 */
        putchar(c);
        return;
    }
    
    item_290004 :
    if (_sw290000_ == STRING) {
        /* item 413 */
        str = obj->data.string.value;
        /* item 414 */
        putchar('"');
    } else {
        goto item_290005;
    }
    
    item_415 :
    if (*str == '\0') {
        /* item 434 */
        putchar('"');
        return;
    } else {
        /* item 4190000 */
        _sw4190000_ = *str;
    }
    
    // item 4190001
    if (_sw4190000_ == '\n') {
        /* item 427 */
        printf("\\n");
        goto item_418;
    } else {
    }
    
    // item 4190002
    if (_sw4190000_ == '\\') {
        /* item 428 */
        printf("\\\\");
        goto item_418;
    } else {
    }
    
    // item 4190003
    if (_sw4190000_ == '"') {
        /* item 429 */
        printf("\\\"");
    } else {
        /* item 432 */
        putchar(*str);
    }
    
    item_418 :
    str++;
    goto item_415;
    
    item_290005 :
    if (_sw290000_ == THE_EMPTY_LIST) {
        /* item 457 */
        printf("()");
        return;
    } else {
    }
    
    // item 290006
    if (_sw290000_ == PAIR) {
        /* item 582 */
        printf("(");
        write_pair(obj);
        printf(")");
        return;
    } else {
    }
    
    // item 290007
    if (_sw290000_ == SYMBOL) {
        /* item 636 */
        printf("%s", obj->data.symbol.value);
        return;
    } else {
        /* item 37 */
        fprintf(stderr, "cannot write unknown type\n");
        /* item 38 */
        exit(1);
        return;
    }
    
}

void write_pair(
    object* pair
) {
    // item 588
    object *car_obj;
    object *cdr_obj;
        
    car_obj = car(pair);
    cdr_obj = cdr(pair);
    write(car_obj);
    
    // item 589
    if (cdr_obj->type == PAIR) {
        /* item 592 */
        printf(" ");
        write_pair(cdr_obj);
        return;
    } else {
    }
    
    // item 593
    if (cdr_obj->type == THE_EMPTY_LIST) {
        return;
    } else {
        /* item 595 */
        printf(" . ");
        write(cdr_obj);
        return;
    }
    
}



