/* Autogenerated with DRAKON Editor 1.14 */
#ifndef CPP_DEMO_H50279
#define CPP_DEMO_H50279

#include "StringList.h"


int main(
    int argc,
    char** argv
);

class SimpleComparer : public IStringComparer
{


public:
    virtual int Compare(
        const std::string* left,
        const std::string* right
    ) const;

};

#endif

